"""T0 initial schema — all TRD section 4 tables

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-01

Creates every table in TRD §4. Run against the Supabase DIRECT connection
(port 5432), never the pooler — see alembic/env.py for why.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intent_mandate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_jws', sa.Text(), nullable=False),
    sa.Column('buyer_id', sa.String(length=200), nullable=False),
    sa.Column('agent_id', sa.String(length=200), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tolerances', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_merchants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nonce', sa.String(length=128), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verify_reason', sa.String(length=64), nullable=True),
    sa.Column('mandate_source', sa.String(length=32), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intent_mandate_nonce'), 'intent_mandate', ['nonce'], unique=False)
    op.create_index(op.f('ix_intent_mandate_buyer_id'), 'intent_mandate', ['buyer_id'], unique=False)
    op.create_table('merchant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('active_config_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authorization',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intent_mandate_id', sa.UUID(), nullable=False),
    sa.Column('ceiling', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CONSUMED', 'EXPIRED', name='authorization_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intent_mandate_id'], ['intent_mandate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('margin_floor_bps', sa.Integer(), nullable=False),
    sa.Column('discount_budget_bps', sa.Integer(), nullable=False),
    sa.Column('return_band_min_days', sa.Integer(), nullable=False),
    sa.Column('return_band_max_days', sa.Integer(), nullable=False),
    sa.Column('shipping_upgrade_allowed', sa.Boolean(), nullable=False),
    sa.Column('shipping_upgrade_max_cost_paise', sa.BigInteger(), nullable=False),
    sa.Column('allowed_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bundle_enabled', sa.Boolean(), nullable=False),
    sa.Column('bundle_max_addon_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('velocity_max_offers_per_buyer_per_hour', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'version', name='uq_merchant_config_version')
    )
    op.create_table('product',
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('list_price_paise', sa.BigInteger(), nullable=False),
    sa.Column('cost_paise', sa.BigInteger(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('stock_version', sa.Integer(), nullable=False),
    sa.Column('return_days', sa.Integer(), nullable=False),
    sa.Column('shipping_days', sa.Integer(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('media', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_index(op.f('ix_product_category'), 'product', ['category'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intent_mandate_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.Enum('GEMINI', 'BASELINE_PASSIVE', 'DETERMINISTIC', name='agent_type'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CONVERTED', 'ABANDONED', 'DENIED', name='session_status'), nullable=False),
    sa.Column('outcome_reason', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['intent_mandate_id'], ['intent_mandate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prev_hash', sa.String(length=128), nullable=False),
    sa.Column('hash', sa.String(length=128), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seq', name='uq_audit_seq')
    )
    op.create_index(op.f('ix_audit_log_session_id'), 'audit_log', ['session_id'], unique=False)
    op.create_table('delegated_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('raw_jws', sa.Text(), nullable=False),
    sa.Column('max_amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('merchant_id', sa.String(length=200), nullable=False),
    sa.Column('nonce', sa.String(length=128), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delegated_token_session_id'), 'delegated_token', ['session_id'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('tool_input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gate_decision', sa.Enum('PASS', 'DENY', 'NA', name='gate_decision'), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'seq', name='uq_event_session_seq')
    )
    op.create_index(op.f('ix_event_session_id'), 'event', ['session_id'], unique=False)
    op.create_table('offer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('base_sku', sa.String(length=64), nullable=False),
    sa.Column('lever_type', sa.Enum('NONE', 'RETURN_EXTENSION', 'SHIPPING_UPGRADE', 'BUNDLE', 'DISCOUNT', 'MULTI', name='lever_type'), nullable=False),
    sa.Column('transformation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_cost_paise', sa.BigInteger(), nullable=False),
    sa.Column('resulting_margin_bps', sa.Integer(), nullable=False),
    sa.Column('within_bounds', sa.Boolean(), nullable=False),
    sa.Column('chosen', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_session_id'), 'offer', ['session_id'], unique=False)
    op.create_table('receipt',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('chain', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('chain_head_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_session_id'), 'receipt', ['session_id'], unique=False)
    op.create_table('cart_mandate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('raw_jws', sa.Text(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_paise', sa.BigInteger(), nullable=False),
    sa.Column('tax_paise', sa.BigInteger(), nullable=False),
    sa.Column('shipping_paise', sa.BigInteger(), nullable=False),
    sa.Column('return_terms_days', sa.Integer(), nullable=False),
    sa.Column('cart_hash', sa.String(length=128), nullable=False),
    sa.Column('nonce', sa.String(length=128), nullable=False),
    sa.Column('merchant_sig', sa.Text(), nullable=False),
    sa.Column('buyer_sig', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_mandate_cart_hash'), 'cart_mandate', ['cart_hash'], unique=False)
    op.create_index(op.f('ix_cart_mandate_session_id'), 'cart_mandate', ['session_id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cart_mandate_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'CAPTURED', 'FAILED', name='payment_status'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cart_mandate_id'], ['cart_mandate.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_index(op.f('ix_cart_mandate_cart_hash'), table_name='cart_mandate')
    op.drop_index(op.f('ix_cart_mandate_session_id'), table_name='cart_mandate')
    op.drop_table('cart_mandate')
    op.drop_index(op.f('ix_receipt_session_id'), table_name='receipt')
    op.drop_table('receipt')
    op.drop_index(op.f('ix_offer_session_id'), table_name='offer')
    op.drop_table('offer')
    op.drop_index(op.f('ix_event_session_id'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_delegated_token_session_id'), table_name='delegated_token')
    op.drop_table('delegated_token')
    op.drop_index(op.f('ix_audit_log_session_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('session')
    op.drop_index(op.f('ix_product_category'), table_name='product')
    op.drop_table('product')
    op.drop_table('merchant_config')
    op.drop_table('authorization')
    op.drop_table('merchant')
    op.drop_index(op.f('ix_intent_mandate_nonce'), table_name='intent_mandate')
    op.drop_index(op.f('ix_intent_mandate_buyer_id'), table_name='intent_mandate')
    op.drop_table('intent_mandate')
    # ### end Alembic commands ###
    op.execute('DROP TYPE IF EXISTS authorization_status')
    op.execute('DROP TYPE IF EXISTS agent_type')
    op.execute('DROP TYPE IF EXISTS session_status')
    op.execute('DROP TYPE IF EXISTS gate_decision')
    op.execute('DROP TYPE IF EXISTS lever_type')
    op.execute('DROP TYPE IF EXISTS payment_status')
